controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
json_version:
    path: /json/version
    controller: App\Controller\JsonController::list